times = ('Atlético Mineiro-MG', 'Flamengo', 'Palmeiras', 'Fortaleza', 'Corinthians', 'Red Bull Bragantino', 'Fluminense', 'America-MG', 'Atlético-GO', 'Santos', 'Ceará', 'Internacional', 'São Paulo', 'Athletico-PR', 'Cuiabá', 'Juventude', 'Grêmio', 'Bahia', 'Sport', 'Chapecoense')
print(f'Lista de times do Brasileirão 2021:\n{times}')
print(28 * '=-=')
print(f'Os 5 primeiros foram:\n{times[0:5]}')
print(28 * '=-=')
print(f'Os 4 ultimos colocados foram:\n{times[-4:]}')
print(28 * '=-=')
print(f'Times em ordem alfabética:\n{sorted(times)}')
print(28 * '=-=')
t = str(input('Você quer ver a colocação de qual time? ')).strip().capitalize()
print(f'O time {t} terminou na {times.index(t)+1}ª coloção no Brasileião 2021!')
print(28 * '=-=')