n = input('Digite algo: ')
print('O tipo primitivo é', type(n))
print('É alfanumérico:', n.isalnum())
print('É alfabético:', n.isalpha())
print('É um número:', n.isnumeric())
print('Está em maiúsculas:', n.isupper())
print('Está em minúsculas:', n.islower())
print('Está capitalizada:', n.istitle())
print('Só tem espaços:', n.isspace())