nome = str(input('Digite seu nome completo: ')).strip()
print('Analizando seu nome...')
print('Seu nome em maiúsculo: {}'.format(nome.upper()))
print('Seu nome em minúsculo: {}'.format(nome.lower()))
print('Seu nome tem {} letras ao todo!'.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome tem {} letras!'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras!'.format(separa[0], len(separa[0])))